backend/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'Customer\HomeController@index')->name('home');

Route::get('categoria/{slug}', 'Customer\CategoryController@index')->name('category');
Route::get('pesquisar/', 'Customer\SearchController@index')->name('search');

Route::get('produto/{slug}', 'Customer\ProductController@index')->name('product');

Route::get('/contato', 'Customer\ContactController@index')->name('contact');
Route::post('/contato', 'Customer\ContactController@store')->name('contact');

Route::group(['prefix' => 'carrinho', 'as' => 'cart.'], function () {
    Route::get('/', 'Customer\CartController@index')->name('index');
    Route::post('/', 'Customer\CartController@store')->name('store');
    Route::get('/delete', 'Customer\CartController@delete')->name('delete.product');
    Route::get('/update', 'Customer\CartController@update')->name('update.product');
    Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function () {
        Route::get('/email', 'Customer\CheckoutController@email')->name('email');
        Route::get('/', 'Customer\CheckoutController@index')->name('index');
        Route::get('/sucesso', 'Customer\CheckoutController@success')->name('success');
        Route::post('/', 'Customer\CheckoutController@store')->name('store');
    });
});

Route::get('postback', 'Customer\CheckoutController@checkout')->name('postback');

// Admin AUTH
Route::group(['prefix' => 'admin', 'namespace' => 'AdminAuth'], function () {
    Route::get('/login', 'LoginController@showLoginForm');
    Route::post('/login', 'LoginController@login');
    Route::post('/logout', 'LoginController@logout')->name('admin.logout');
    // Route::get('/register', 'Auth\RegisterController@showAdminRegisterForm')->name('admin.register');
    // Route::post('/register', 'Auth\RegisterController@register');
});
// Customer AUTH
Route::group(['prefix' => 'customer', 'namespace' => 'CustomerAuth'], function () {
    Route::get('/login', 'LoginController@showLoginForm');
    Route::post('/login', 'LoginController@login');
    Route::get('/register', 'RegisterController@showRegisterForm')->name('admin.register');
    Route::post('/register', 'RegisterController@register');
    Route::get('/logout', 'LoginController@logout')->name('customer.logout');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    // Promoção relâmpago
    Route::group(['prefix' => 'pedido', 'as' => 'order.'], function () {
        Route::get('/', 'Admin\OrderController@index')->name('index');
        Route::get('/create', 'Admin\OrderController@create')->name('create');
        Route::post('/store', 'Admin\OrderController@store')->name('store');
        Route::get('/edit/{order}', 'Admin\OrderController@edit')->name('edit');
        Route::put('/update/{order}', 'Admin\OrderController@update')->name('update');
        Route::delete('/delete/{order}', 'Admin\OrderController@delete')->name('delete');
    });
    Route::group(['prefix' => 'promocao', 'as' => 'promotion.'], function () {
        Route::group(['prefix' => 'relampago', 'as' => 'flash.'], function () {
            Route::get('/', 'Admin\FlashController@index')->name('index');
            Route::get('/create', 'Admin\FlashController@create')->name('create');
            Route::post('/store', 'Admin\FlashController@store')->name('store');
            Route::get('/edit/{flash}', 'Admin\FlashController@edit')->name('edit');
            Route::put('/update/{flash}', 'Admin\FlashController@update')->name('update');
            Route::delete('/delete/{flash}', 'Admin\FlashController@delete')->name('delete');
        });
    });
    // Contato
    Route::group(['prefix' => 'contato', 'as' => 'contact.'], function () {
        Route::get('/', 'Admin\ContactController@index')->name('index');
        Route::get('/edit/{contact}', 'Admin\ContactController@edit')->name('edit');
        Route::put('/update/{contact}', 'Admin\ContactController@update')->name('update');
        Route::delete('/delete/{contact}', 'Admin\ContactController@delete')->name('delete');
    });
    Route::group(['prefix' => 'newsletter', 'as' => 'newsletter.'], function () {
        Route::get('/', 'Admin\NewsletterController@index')->name('index');
        Route::delete('/delete/{newsletter}', 'Admin\NewsletterController@delete')->name('delete');
    });
    // Clientes
    Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
        Route::get('/', 'Admin\CustomerController@index')->name('index');
        Route::get('/create', 'Admin\CustomerController@create')->name('create');
        Route::post('/store', 'Admin\CustomerController@store')->name('store');
        Route::get('/edit/{customer}', 'Admin\CustomerController@edit')->name('edit');
        Route::put('/update/{customer}', 'Admin\CustomerController@update')->name('update');
        Route::delete('/delete/{customer}', 'Admin\CustomerController@delete')->name('delete');
    });
    // Catálogo
    Route::group(['prefix' => 'catalogo'], function () {
        // Categorias
        Route::group(['prefix' => 'categoria', 'as' => 'category.'], function () {
            Route::get('/', 'Admin\CategoryController@index')->name('index');
            Route::get('/create', 'Admin\CategoryController@create')->name('create');
            Route::post('/store', 'Admin\CategoryController@store')->name('store');
            Route::get('/edit/{category}', 'Admin\CategoryController@edit')->name('edit');
            Route::put('/update/{category}', 'Admin\CategoryController@update')->name('update');
            Route::delete('/delete/{category}', 'Admin\CategoryController@delete')->name('delete');
        });

        // Subcategorias
        Route::group(['prefix' => 'subcategoria', 'as' => 'subcategory.'], function () {
            Route::post('/store', 'Admin\SubcategoryController@store')->name('store');
            Route::delete('/delete/{subcategory}', 'Admin\SubcategoryController@delete')->name('delete');
        });
        // Tags
        Route::group(['prefix' => 'tag', 'as' => 'tag.'], function () {
            Route::get('/', 'Admin\TagController@index')->name('index');
            Route::get('/create', 'Admin\TagController@create')->name('create');
            Route::post('/store', 'Admin\TagController@store')->name('store');
            Route::get('/edit/{tag}', 'Admin\TagController@edit')->name('edit');
            Route::put('/update/{tag}', 'Admin\TagController@update')->name('update');
            Route::delete('/delete/{tag}', 'Admin\TagController@delete')->name('delete');
        });
        // Cores
        Route::group(['prefix' => 'color', 'as' => 'color.'], function () {
            Route::get('/', 'Admin\ColorController@index')->name('index');
            Route::get('/create', 'Admin\ColorController@create')->name('create');
            Route::post('/store', 'Admin\ColorController@store')->name('store');
            Route::get('/edit/{color}', 'Admin\ColorController@edit')->name('edit');
            Route::put('/update/{color}', 'Admin\ColorController@update')->name('update');
            Route::delete('/delete/{color}', 'Admin\ColorController@delete')->name('delete');
        });

        Route::group(['prefix' => 'variacao', 'as' => 'variation.'], function () {
            Route::get('/', 'Admin\VariationController@index')->name('index');
            Route::get('/create', 'Admin\VariationController@create')->name('create');
            Route::post('/store', 'Admin\VariationController@store')->name('store');
            Route::get('/edit/{variation}', 'Admin\VariationController@edit')->name('edit');
            Route::put('/update/{variation}', 'Admin\VariationController@update')->name('update');
            Route::delete('/delete/{variation}', 'Admin\VariationController@delete')->name('delete');

            Route::group(['prefix' => 'option', 'as' => 'option.'], function () {
                Route::post('store/', 'Admin\VariationOptionController@store')->name('store');
                Route::put('update/{option}', 'Admin\VariationOptionController@update')->name('update');
                Route::delete('delete/{option}', 'Admin\VariationOptionController@delete')->name('delete');
            });
        });
        // Produtos
        Route::group(['prefix' => 'produtos', 'as' => 'product.'], function () {
            Route::get('/', 'Admin\ProductController@index')->name('index');
            Route::get('/create', 'Admin\ProductController@create')->name('create');
            Route::post('/store', 'Admin\ProductController@store')->name('store');
            Route::get('/edit/{product}', 'Admin\ProductController@edit')->name('edit');
            Route::get('/status/{product}', 'Admin\ProductController@status')->name('status');
            Route::put('/update/{product}', 'Admin\ProductController@update')->name('update');
            Route::delete('/delete/{product}', 'Admin\ProductController@delete')->name('delete');
            // Imagem do produto
            Route::group(['prefix' => 'image', 'as' => 'image.'], function () {
                Route::get('list/{id}', 'Admin\ProductImageController@list')->name('list');
                Route::post('sort/', 'Admin\ProductImageController@sort')->name('sort');
                Route::post('/', 'Admin\ProductImageController@store')->name('store');
                Route::delete('/delete/{file}', 'Admin\ProductImageController@delete')->name('delete');
            });

backend/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'description',
        'slug',
        'meta_title',
        'meta_description',
        'show',
        'tag_id',
        'primary',
        'new',
        'sale',
        'has_free_shipping',
        'promotional_price',
        'price',
        'stock',
        'measurement_guide',
        'weight',
        'depth',
        'use_subproduct',
        'width',
        'height',
        'sku',
        'barcode',
    ];

    protected $appends = [
        'main_image',
        'toggle',
    ];

    protected $dates = [
        'updated_at',
    ];

    public function images()
    {
        return $this->hasMany('App\Models\ProductImage', 'product_id');
    }

    public function products()
    {
        return $this->hasMany('App\Models\Subproduct', 'product_id');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Models\Category', 'product_categories', 'product_id', 'category_id');
    }

    public function variations()
    {
        return $this->belongsToMany('App\Models\Variation', 'product_variations', 'product_id', 'variation_id');
    }
    public function tag()
    {
        return $this->belongsTo('App\Models\Tag');
    }

    public function mainProductImage()
    {
        return $this->images()->where('position', 1)->first();
    }

    public function getMainImageAttribute($value)
    {
        if (count($this->images)) {
            return asset('uploads/products/thumbnail/' . $this->images->firstWhere('position', 1)->file);
        } else {
            return asset('img/no-photo-50.png');
        }
    }
    public function getToggleAttribute($value)
    {
        return $this->attributes['show'] == 1 ? 'toggle-on' : 'toggle-off';
    }
    public function getUpdatedAtAttribute($value)
    {
        return convertDateUSAToBrazil($this->attributes['updated_at']);
    }

}

backend/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Color;
use App\Models\Product;
use App\Models\Tag;
use App\Services\ProductService;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        $products = ProductService::index($request->all(), null, 30);
        return view('admin.pages.product.index')
            ->with('products', $products);
    }
    public function create()
    {
        return view('admin.pages.product.create');
    }

    public function store(ProductRequest $request)
    {
        $product = ProductService::create($request->all());
        return \redirect()
            ->route('admin.product.edit', ['product' => $product])
            ->with('success', 'Produto cadastrado com sucesso');
    }
    public function edit(Product $product)
    {
        $tags = Tag::get();
        $categories = Category::whereNull('parent_id')->get();
        $colors = Color::get();

        $categoriesId = $product->categories()->pluck('categories.id')->toArray();
        return view('admin.pages.product.edit')
            ->with('categoriesId', $categoriesId)
            ->with('categories', $categories)
            ->with('tags', $tags)
            ->with('colors', $colors)
            ->with('product', $product);
    }

    public function status(Product $product)
    {
        $show = $product->show == 0 ? 1 : 0;
        $product->update([
            'show' => $show,
        ]);
        return \redirect()
            ->back()
            ->with('success', 'Status atualizado com sucesso');
    }

    public function update(Product $product, ProductRequest $request)
    {
        ProductService::update($request->all(), $product);
        return \redirect()
            ->back()
            ->with('success', 'Produto editado com sucesso');
    }

    public function delete(Product $product)
    {
        ProductService::delete($product);
        return \redirect()
            ->back()
            ->with('success', 'Produto removido com sucesso');
    }
}

backend/app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Services\ProductService;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        if(\validateRequest('category_id')){
            $category = Category::find($request->category_id);
            $products = $category->products;
        }else{
            $products = productSearch($request->search_string);
        }
        $products = $products->filter(function ($product) {
            if ($product->images()->count() > 0) {
                return $product;
            }
        });

        $products_id = $products->pluck('id')->toArray();
        $products = ProductService::index($request->all(), $products_id);
        return view('customer.components.filter-products')
        ->with('products', $products);
    }
}

backend/app/Http/Controllers/Customer/ProductController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Models\Color;
use App\Models\Product;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function index($slug)
    {
        $product = Product::where('slug', $slug)->first();

        $subproductId = $product->products()->pluck('id')->toArray();

        $variationQuery = \DB::table('variation_options')
            ->join('variations', 'variations.id', '=', 'variation_options.variation_id')
            ->join('subproduct_variation_options', 'subproduct_variation_options.variation_option_id', '=', 'variation_options.id')
            ->whereIn('subproduct_id', $subproductId);
        $variations = $variationQuery
            ->select(
                'variations.id',
                'variations.name',
            )
            ->groupBy('variations.id', 'variations.name')
            ->get();

        $variationOptions = $variationQuery
            ->select(
                'variation_options.id',
                'variation_options.variation_id',
                'variation_options.name',
            )
            ->groupBy('variation_options.id', 'variation_options.name', 'variation_options.variation_id')
            ->get();

        $categoriesId = $product->categories()
            ->pluck('categories.id')
            ->toArray();

        $colors = Color::whereIn('id', $product->products()->pluck('color_id')->toArray())->get();

        $relatedProducts = $categoriesId != [] ? Product::join('product_categories', 'products.id', '=', 'product_categories.product_id')
            ->where('category_id', $categoriesId)
            ->where('products.id', "<>", $product->id)->get() : collect([]);

        return view('customer.pages.product.index')
            ->with('variations', $variations)
            ->with('colors', $colors)
            ->with('variationOptions', $variationOptions)
            ->with('relatedProducts', $relatedProducts)
            ->with('product', $product);
    }
}

backend/resources/views/admin/pages/product/index.blade.php
@extends('admin.templates.default', ['activePage' => 'product', 'titlePage' => __('Produtos')])

@section('title', 'Produtos')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Produtos</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <div class="float-right">
                            <a href="{{ route('admin.product.create') }}">
                                <button class="btn btn-success act-include">
                                    Adicionar
                                </button>
                            </a>
                        </div>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-12">
                        <div class="card card-info card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Lista de Produtos</h3>
                                <div class="card-tools">
                                    <?php
                                    $paginate = $products;

                                    $link_limit = 7;

                                    $filters = '';
                                    // $filters .= '&init_date=' . request('init_date');
                                    // $filters .= '&final_date=' . request('final_date');
                                    // $filters .= '&orderby=' . request('orderby');
                                    // $filters .= '&ordenation=' . request('ordenation');
                                    // $filters .= '&reference=' . request('reference');
                                    // $filters .= '&name=' . request('name');
                                    // $filters .= '&tag_id=' . request('tag_id');
                                    // $filters .= '&provider_id=' . request('provider_id');
                                    // $filters .= '&alert=' . request('alert');
                                    ?>

                                    @if ($paginate->lastPage() > 1)
                                        <ul class="pagination pagination-sm float-right">
                                            <li class="page-item {{ $paginate->currentPage() == 1 ? ' disabled' : '' }}">
                                                <a class="page-link" href="{{ $paginate->url(1) . $filters }}">«</a>
                                            </li>
                                            @for ($i = 1; $i <= $paginate->lastPage(); $i++)
                                                <?php
                                                $half_total_links = floor($link_limit / 2);
                                                $from = $paginate->currentPage() - $half_total_links;
                                                $to = $paginate->currentPage() + $half_total_links;
                                                if ($paginate->currentPage() < $half_total_links) { $to +=$half_total_links
                                                    - $paginate->currentPage();
                                                    }
                                                    if ($paginate->lastPage() - $paginate->currentPage() <
                                                        $half_total_links) { $from -=$half_total_links - ($paginate->
                                                        lastPage() - $paginate->currentPage()) - 1;
                                                        }
                                                        ?>
                                                        @if ($from < $i && $i < $to)
                                                            <li
                                                                class="page-item {{ $paginate->currentPage() == $i ? ' active' : '' }}">
                                                                <a class="page-link" href="{{ $paginate->url($i) . $filters }}">{{ $i }}</a>
                                                            </li>
                                                        @endif
                                            @endfor
                                            <li
                                                class="page-item {{ $paginate->currentPage() == $paginate->lastPage() ? ' disabled' : '' }}">
                                                <a class="page-link" href="{{ $paginate->url($paginate->lastPage()) . $filters }}">»</a>
                                            </li>
                                        </ul>
                                    @endif
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-3">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nome</th>
                                            <th>Ult. Atualização</th>
                                            <th>Disponível</th>
                                            <th>Ações</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse($products as $product)
                                            <tr>
                                            <td>
                                                <img class="photo" src="{{$product->main_image}}" alt="{{$product->name}}">
                                            </td>
                                                <td>{{ $product->name }}</td>
                                                <td>{{ $product->updated_at }}</td>
                                                <td class="text-center align-middle py-0">
                                                    <div class="btn-group btn-group-sm">
                                                        <a href="{{ route('admin.product.status', ['product' => $product->id]) }}"
                                                            class="btn btn-info">
                                                            <i class="fas fa-{{$product->toggle}}"></i>
                                                        </a>
                                                    </div>
                                                </td>
                                                <td class="text-center align-middle py-0">
                                                    <div class="btn-group btn-group-sm">
                                                        <a href="{{ route('product', ['slug' => $product->slug]) }}" target="_blank"
                                                            class="btn btn-info" title="Visualizar no Site">
                                                            <i class="fas fa-external-link-alt"></i>
                                                        </a>
                                                        <a href="{{ route('admin.product.edit', ['product' => $product->id]) }}"
                                                            class="btn btn-info">
                                                            <i class="fa fa-edit"></i>
                                                        </a>
                                                        <button onclick="deleteItem(this, 1)"
                                                            data-href="{{ route('admin.product.delete', ['product' => $product->id]) }}"
                                                            class="btn btn-danger act-delete">
                                                            <i class="fa fa-trash"></i>
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan=6>Nenhum dado cadastrado</td>
                                            </tr>
                                        @endforelse

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>

                    <!-- ./col -->
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection