antigo/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', 'Customer\HomeController@index');
Route::get('/search', 'Customer\SearchController@index')->name('search');
Route::get('/product/{slug}', 'Customer\ProductController@index')->name('product');
Route::get('/checkout', 'Customer\CheckoutController@index')->name('checkout');
Route::post('/checkout', 'Customer\CheckoutController@store')->name('store');

Route::group(['prefix' => 'carrinho', 'as' => 'cart.'], function(){
    Route::get('/', 'Customer\CartController@index')->name('index');
    Route::post('/cart', 'Customer\CartController@store')->name('store');

});


Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
Route::group(['prefix' => 'admin'], function(){
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::get('/register', 'Auth\RegisterController@showAdminRegisterForm')->name('admin.register');
    Route::post('/register', 'Auth\RegisterController@createAdmin');
    Route::post('/logout', 'Auth\RegisterController@logout')->name('admin.logout');

});

Route::get('/login/customer', 'Auth\LoginController@showCustomerLoginForm');
Route::get('/register/customer', 'Auth\RegisterController@showCustomerRegisterForm');
Route::post('/login/customer', 'Auth\LoginController@customerLogin');
Route::post('/register/customer', 'Auth\RegisterController@createCustomer');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    // Categorias
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::group(['prefix' => 'categoria', 'as' => 'category.'], function () {
        Route::get('/', 'Admin\CategoryController@index')->name('index');
        Route::get('/create', 'Admin\CategoryController@create')->name('create');
        Route::post('/store', 'Admin\CategoryController@store')->name('store');
        Route::get('/edit/{category}', 'Admin\CategoryController@edit')->name('edit');
        Route::put('/update/{category}', 'Admin\CategoryController@update')->name('update');
        Route::delete('/delete/{category}', 'Admin\CategoryController@delete')->name('delete');
    });
    Route::group(['prefix' => 'variacao', 'as' => 'variation.'], function () {
        Route::get('/', 'Admin\VariationController@index')->name('index');
        Route::get('/create', 'Admin\VariationController@create')->name('create');
        Route::post('/store', 'Admin\VariationController@store')->name('store');
        Route::get('/edit/{variation}', 'Admin\VariationController@edit')->name('edit');
        Route::put('/update/{variation}', 'Admin\VariationController@update')->name('update');
        Route::delete('/delete/{variation}', 'Admin\VariationController@delete')->name('delete');
        Route::put('option/update/{option}', 'Admin\VariationController@optionUupdate')->name('option.update');
        Route::delete('option/delete/{option}', 'Admin\VariationController@optionDelete')->name('option.delete');
    });
    // Produtos
    Route::group(['prefix' => 'produtos', 'as' => 'product.'], function () {
        Route::get('/', 'Admin\ProductController@index')->name('index');
        Route::get('/create', 'Admin\ProductController@create')->name('create');
        Route::post('/store', 'Admin\ProductController@store')->name('store');
        Route::get('/edit/{product}', 'Admin\ProductController@edit')->name('edit');
        Route::put('/update/{product}', 'Admin\ProductController@update')->name('update');
        Route::delete('/delete/{product}', 'Admin\ProductController@delete')->name('delete');
        // Imagem do produto
        Route::group(['prefix' => '{product}/image', 'as' => 'image.'], function () {
            Route::post('/', 'Admin\ProductImageController@store')->name('store');
            Route::delete('/delete/{category}', 'Admin\ProductImageController@delete')->name('delete');
        });
        // Categoria do Produto
        Route::group(['prefix' => '{product}/category', 'as' => 'category.'], function () {
            Route::post('/', 'Admin\ProductCategoryController@store')->name('store');
            Route::delete('/delete/{category}', 'Admin\ProductCategoryController@delete')->name('delete');
        });
        // Tag do produto
        Route::group(['prefix' => '{product}/tag', 'as' => 'tag.'], function () {
            Route::post('/', 'Admin\ProductTagController@store')->name('store');
            Route::delete('/delete/{tag}', 'Admin\ProductTagController@delete')->name('delete');
        });
        // Variação do produto
        Route::group(['prefix' => '{product}/variation', 'as' => 'variation.'], function () {
            Route::post('/', 'Admin\ProductVariationController@store')->name('store');
            Route::delete('/delete/{variation}', 'Admin\ProductVariationController@delete')->name('delete');
        });
    });
});

    Route::get('table-list', function () {
        return view('pages.table_list');
    })->name('table');

    Route::get('typography', function () {
        return view('pages.typography');
    })->name('typography');

    Route::get('icons', function () {
        return view('pages.icons');
    })->name('icons');

    Route::get('map', function () {
        return view('pages.map');
    })->name('map');

    Route::get('notifications', function () {
        return view('pages.notifications');
    })->name('notifications');

    Route::get('rtl-support', function () {
        return view('pages.language');
    })->name('language');

    Route::get('upgrade', function () {
        return view('pages.upgrade');
    })->name('upgrade');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

antigo/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        "parent_id",
        "name",
        "slug",
        "meta_description",
        "meta_title",
        "status",
    ];

    public function categories()
    {
        return $this->hasMany('App\Models\Category','parent_id');
    }


}

antigo/app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use App\Services\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
        $categories = CategoryService::index($request);
        return view('admin.pages.category.index')
            ->with('categories', $categories);
    }
    public function create()
    {
        return view('admin.pages.category.create');
    }

    public function store(CategoryRequest $request)
    {
        $category = CategoryService::create($request->all());
        return \redirect()
            ->route('admin.category.edit', ['category' => $category])
            ->with('success', 'Categoria cadastrada com sucesso');
    }
    public function edit(Category $category)
    {
        return view('admin.pages.category.edit')
            ->with('category', $category);
    }

    public function update(Category $category, CategoryRequest $request)
    {
        CategoryService::update($request->all(), $category);
        return \redirect()
            ->back()
            ->with('success', 'Categoria editada com sucesso');
    }

    public function delete(Category $category)
    {
        CategoryService::delete($category);
        return \redirect()
            ->back()
            ->with('success', 'Categoria removida com sucesso');
    }

}

antigo/app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Services\CategoryService;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
        $categories = CategoryService::index($request);

        return \response()->json($categories,200 );
    }
}

antigo/resources/views/admin/pages/category/create.blade.php
@extends('admin.templates.default', ['activePage' => 'category', 'titlePage' => __('Categorias')])
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <form method="post" action="{{ route('admin.category.store') }}" autocomplete="off" class="form-horizontal">
                    @csrf

                    <div class="card ">
                        <div class="card-header card-header-info">
                            <h4 class="card-title">{{ __('Criar Categoria') }}</h4>
                            <p class="card-category">{{ __('Dados da categoria') }}</p>
                        </div>
                        <div class="card-body ">
                            <div class="row">
                                <label class="col-sm-3 col-form-label">{{ __('Nome') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                        <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                            name="name" id="input-name" type="text" placeholder="{{ __('Nome') }}"
                                            value="{{ old('name') }}" required="true"
                                            aria-required="true" />
                                        @if ($errors->has('name'))
                                        <span id="name-error" class="error text-danger"
                                            for="input-name">{{ $errors->first('name') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 col-form-label">{{ __('URL da categoria') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group{{ $errors->has('slug') ? ' has-danger' : '' }}">
                                        <input class="input-slug form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}"
                                            name="slug" id="input-slug" type="text" placeholder="{{ __('URL da categoria') }}"
                                            value="{{ old('slug') }}" required="true"
                                            aria-required="true" />
                                        @if ($errors->has('slug'))
                                        <span id="slug-error" class="error text-danger"
                                            for="input-slug">{{ $errors->first('slug') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 col-form-label">{{ __('Título para SEO') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group{{ $errors->has('meta_title') ? ' has-danger' : '' }}">
                                        <input class="form-control{{ $errors->has('meta_title') ? ' is-invalid' : '' }}"
                                            name="meta_title" id="input-meta_title" type="text" placeholder="{{ __('Título para SEO') }}"
                                            value="{{ old('meta_title') }}" required="true"
                                            aria-required="true" />
                                        @if ($errors->has('meta_title'))
                                        <span id="meta_title-error" class="error text-danger"
                                            for="input-meta_title">{{ $errors->first('meta_title') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-sm-3 col-form-label">{{ __('Descrição para SEO') }}</label>
                                <div class="col-sm-7">
                                    <div class="form-group{{ $errors->has('meta_description') ? ' has-danger' : '' }}">
                                        <input class="form-control{{ $errors->has('meta_description') ? ' is-invalid' : '' }}"
                                            name="meta_description" id="input-meta_description" type="text" placeholder="{{ __('Descrição para SEO') }}"
                                            value="{{ old('meta_description') }}" required="true"
                                            aria-required="true" />
                                        @if ($errors->has('meta_description'))
                                        <span id="meta_description-error" class="error text-danger"
                                            for="input-meta_description">{{ $errors->first('meta_description') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-info">{{ __('Adicionar') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

antigo/resources/views/admin/pages/category/index.blade.php
@extends('admin.templates.default', ['activePage' => 'category', 'titlePage' => __('Categorias')])
@section('content')

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title ">Lista de Categorias</h4>
                        <p class="card-category"> Cadastre as categorias que tem no seu site</p>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 text-right">
                                <a href="{{route('admin.category.create')}}" class="btn btn-sm btn-info">Adicionar</a>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-info">
                                    <tr>
                                        <th>Nome</th>
                                        <th>URL da Categoria</th>
                                        <th>Título para SEO</th>
                                        <th>Descrição para SEO</th>
                                        <th class="text-right">Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="addSubcategory display-none">
                                        <form action="{{route('admin.category.store')}}" method="post"
                                            autocomplete="off">
                                            @csrf
                                            <input type="hidden" name="parent_id" id="parent_id">
                                            <td>
                                                <div class="form-group">
                                                    <input class="form-control" name="name" id="input-name" type="text"
                                                        placeholder="{{ __('Nome') }}" value="{{ old('name') }}"
                                                        required="true" aria-required="true" />
                                                    <span id="name-error" class="error text-danger display-none"
                                                        for="input-name"></span>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="form-group">
                                                    <input class="form-control input-slug" name="slug" id="input-slug"
                                                        type="text" placeholder="{{ __('URL da Categoria') }}"
                                                        value="{{ old('slug') }}" required="true"
                                                        aria-required="true" />
                                                    <span id="slug-error" class="error text-danger display-none"
                                                        for="input-slug"></span>
                                                </div>

                                            </td>
                                            <td>
                                                <div class="form-group">
                                                    <input class="form-control" name="meta_title" id="input-meta_title"
                                                        type="text" placeholder="{{ __('Título para SEO') }}"
                                                        value="{{ old('meta_title') }}" required="true"
                                                        aria-required="true" />
                                                    <span id="meta_title-error" class="error text-danger display-none"
                                                        for="input-meta_title">{{ $errors->first('meta_title') }}</span>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="form-group">
                                                    <input class="form-control" name="meta_description"
                                                        id="input-meta_description" type="text"
                                                        placeholder="{{ __('Descrição para SEO') }}"
                                                        value="{{ old('meta_description') }}" required="true"
                                                        aria-required="true" />
                                                    <span id="meta_description-error"
                                                        class="error text-danger display-none"
                                                        for="input-meta_description"></span>
                                                </div>
                                            </td>

                                            <td class="td-actions text-right">
                                                <div class="btn-group">
                                                    <a rel="tooltip" class="btn btn-link btn-success storeCategory"
                                                        href="#">
                                                        <i class="material-icons">done</i>
                                                        <div class="ripple-container"></div>
                                                    </a>
                                                    <a rel="tooltip" class="btn btn-link btn-danger cancelCategory"
                                                        href="#">
                                                        <i class="material-icons">close</i>
                                                        <div class="ripple-container"></div>
                                                    </a>
                                                </div>
                                            </td>
                                        </form>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@stack('js')
@endsection

@section('scripts')
<script type="text/javascript">
var categories = '';
window.onload = async ()=> {
    categories = await getCategories();
    const firstCategories = categories.data.filter(item => !item.parent_id);
    firstCategories.forEach(category => createTreeView(category));
}

const getCategories = async()=> {
    return await axios.get("{{route('api.category.index')}}")
    .then(response => response.data);
}

const createTreeView = async (category) => {
    let tbody = $('tbody');

    let urlEdit = "{{route('admin.category.edit', ['category' =>'idCategory'])}}";
    urlEdit.replace('idCategory', category.id);

    let urlDelete = "{{route('admin.category.delete', ['category' =>'idCategory'])}}";
    urlDelete.replace('idCategory', category.id);

    let trCategory = $("<tr>");
    let tdName = $("<td>", {
        text: category.name
    });
    let tdSlug = $("<td>", {
        text: category.slug
    });
    let tdMetaTitle = $("<td>", {
        text: category.meta_title
    });
    let tdMetaDescription = $("<td>", {
        text: category.meta_description
    });
    let tdActions = $("<td>", {
        class: "td-actions text-right"
    });
    let divBtnGroup = $("<div>", {
        class: "btn-group"
    });

    let btnAddChildren = $("<a>", {
        "data-parent_id": category.id,
        class: "btn btn-info subcategory",
        href: "#"
    });
    let iconAddChildren = $("<i>", {
        class: "material-icons",
        text: "add"
    });

    let btnEdit = $("<a>", {
        "data-parent_id": category.id,
        class: "btn btn-info",
        href: urlEdit
    });
    let iconEdit = $("<i>", {
        class: "material-icons",
        text: "edit"
    });
    let btnDelete = $("<a>", {
        "data-parent_id": category.id,
        class: "btn btn-danger btn-delete",
        href: '#'
    });
    let iconDelete = $("<i>", {
        class: "material-icons",
        text: "delete"
    });
    let formDelete = $("<form>", {
        id: "delete-form",
        action: urlDelete,
        method: 'post',
        class: "display-none"
    });

    let inputToken = $("<input>", {
        type: "hidden",
        name: "_token",
        value: "{{ csrf_token() }}"
    });
    let inputMethod = $("<input>", {
        type: "hidden",
        name: "_method",
        value: "delete"
    });

    // Formulário de Exclusão
    formDelete.append(inputToken);
    formDelete.append(inputMethod);

    // Grupo de Botões
    btnAddChildren.append(iconAddChildren);
    btnEdit.append(iconEdit);
    btnDelete.append(iconDelete);

    divBtnGroup.append(btnAddChildren);
    divBtnGroup.append(btnEdit);
    divBtnGroup.append(btnDelete);
    // TD Actions
    tdActions.append(divBtnGroup);
    // TR Completa
    trCategory.append(tdName);
    trCategory.append(tdSlug);
    trCategory.append(tdMetaTitle);
    trCategory.append(tdMetaDescription);
    trCategory.append(tdActions);
    trCategory.append(formDelete);
    tbody.append(trCategory);

    const children = categories.data.filter(child => child.parent_id === category.id);
    if (children.length > 0) {
        children.map(createTreeView);
    }
}


$('.btn-delete').on('click', function() {
    $('#delete-form').submit();
});
$(document).on('click','.subcategory', function(e) {
    e.preventDefault();

    let icon = $(this).find('i');
    let trForm = $('.addSubcategory');

    if (icon.text() == 'add') {
        icon.text('remove');

        let parent_id = $(this).data('parent_id');

        trForm.removeClass('display-none');

        trForm.find('input[name=parent_id]').val(parent_id);
    } else {
        $(this).find('i').text('add');
        trForm.addClass('display-none');
    }
});

let btnStore = document.querySelector('.storeCategory');
// let cancelStore = document.querySelector('.cancelCategory');

btnStore.addEventListener("click", (e) => {
    e.preventDefault();
    let form = $('.addSubcategory form');
    let data = form.serialize();
    let url = form.attr('action');
    axios.post(url, data)
        .then((response) => {
            location.reload();
            console.log(response);
        })
        .catch(function(error) {
            validateError(error.response);
        });
});

const validateError = (response) => {
    const {
        status
    } = response;
    if (status === 422) {
        const {
            data: {
                errors
            }
        } = response;

        for (error in errors) {
            let elementError = $(`input[name=${error}]`);
            let spanError = $(`#${error}-error`);

            elementError.addClass('is-invalid');
            elementError.parent().addClass('has-error');
            spanError.removeClass('display-none');
            spanError.text(errors[error]);
        }
    }

}
</script>
@endsection