antigo/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', 'Customer\HomeController@index');
Route::get('/search', 'Customer\SearchController@index')->name('search');
Route::get('/product/{slug}', 'Customer\ProductController@index')->name('product');
Route::get('/checkout', 'Customer\CheckoutController@index')->name('checkout');
Route::post('/checkout', 'Customer\CheckoutController@store')->name('store');

Route::group(['prefix' => 'carrinho', 'as' => 'cart.'], function(){
    Route::get('/', 'Customer\CartController@index')->name('index');
    Route::post('/cart', 'Customer\CartController@store')->name('store');

});


Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
Route::group(['prefix' => 'admin'], function(){
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::get('/register', 'Auth\RegisterController@showAdminRegisterForm')->name('admin.register');
    Route::post('/register', 'Auth\RegisterController@createAdmin');
    Route::post('/logout', 'Auth\RegisterController@logout')->name('admin.logout');

});

Route::get('/login/customer', 'Auth\LoginController@showCustomerLoginForm');
Route::get('/register/customer', 'Auth\RegisterController@showCustomerRegisterForm');
Route::post('/login/customer', 'Auth\LoginController@customerLogin');
Route::post('/register/customer', 'Auth\RegisterController@createCustomer');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    // Categorias
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::group(['prefix' => 'categoria', 'as' => 'category.'], function () {
        Route::get('/', 'Admin\CategoryController@index')->name('index');
        Route::get('/create', 'Admin\CategoryController@create')->name('create');
        Route::post('/store', 'Admin\CategoryController@store')->name('store');
        Route::get('/edit/{category}', 'Admin\CategoryController@edit')->name('edit');
        Route::put('/update/{category}', 'Admin\CategoryController@update')->name('update');
        Route::delete('/delete/{category}', 'Admin\CategoryController@delete')->name('delete');
    });
    Route::group(['prefix' => 'variacao', 'as' => 'variation.'], function () {
        Route::get('/', 'Admin\VariationController@index')->name('index');
        Route::get('/create', 'Admin\VariationController@create')->name('create');
        Route::post('/store', 'Admin\VariationController@store')->name('store');
        Route::get('/edit/{variation}', 'Admin\VariationController@edit')->name('edit');
        Route::put('/update/{variation}', 'Admin\VariationController@update')->name('update');
        Route::delete('/delete/{variation}', 'Admin\VariationController@delete')->name('delete');
        Route::put('option/update/{option}', 'Admin\VariationController@optionUupdate')->name('option.update');
        Route::delete('option/delete/{option}', 'Admin\VariationController@optionDelete')->name('option.delete');
    });
    // Produtos
    Route::group(['prefix' => 'produtos', 'as' => 'product.'], function () {
        Route::get('/', 'Admin\ProductController@index')->name('index');
        Route::get('/create', 'Admin\ProductController@create')->name('create');
        Route::post('/store', 'Admin\ProductController@store')->name('store');
        Route::get('/edit/{product}', 'Admin\ProductController@edit')->name('edit');
        Route::put('/update/{product}', 'Admin\ProductController@update')->name('update');
        Route::delete('/delete/{product}', 'Admin\ProductController@delete')->name('delete');
        // Imagem do produto
        Route::group(['prefix' => '{product}/image', 'as' => 'image.'], function () {
            Route::post('/', 'Admin\ProductImageController@store')->name('store');
            Route::delete('/delete/{category}', 'Admin\ProductImageController@delete')->name('delete');
        });
        // Categoria do Produto
        Route::group(['prefix' => '{product}/category', 'as' => 'category.'], function () {
            Route::post('/', 'Admin\ProductCategoryController@store')->name('store');
            Route::delete('/delete/{category}', 'Admin\ProductCategoryController@delete')->name('delete');
        });
        // Tag do produto
        Route::group(['prefix' => '{product}/tag', 'as' => 'tag.'], function () {
            Route::post('/', 'Admin\ProductTagController@store')->name('store');
            Route::delete('/delete/{tag}', 'Admin\ProductTagController@delete')->name('delete');
        });
        // Variação do produto
        Route::group(['prefix' => '{product}/variation', 'as' => 'variation.'], function () {
            Route::post('/', 'Admin\ProductVariationController@store')->name('store');
            Route::delete('/delete/{variation}', 'Admin\ProductVariationController@delete')->name('delete');
        });
    });
});

    Route::get('table-list', function () {
        return view('pages.table_list');
    })->name('table');

    Route::get('typography', function () {
        return view('pages.typography');
    })->name('typography');

    Route::get('icons', function () {
        return view('pages.icons');
    })->name('icons');

    Route::get('map', function () {
        return view('pages.map');
    })->name('map');

    Route::get('notifications', function () {
        return view('pages.notifications');
    })->name('notifications');

    Route::get('rtl-support', function () {
        return view('pages.language');
    })->name('language');

    Route::get('upgrade', function () {
        return view('pages.upgrade');
    })->name('upgrade');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

antigo/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'description',
        'slug',
        'meta_title',
        'meta_description',
        'show',
        'primary',
        'new',
        'sale',
        'has_free_shipping',
        'promotional_price',
        'price',
        'stock',
        'weight',
        'depth',
        'width',
        'height',
        'sku',
        'barcode',
    ];

    public function images()
    {
        return $this->hasMany('App\Models\ProductImage', 'product_id');
    }

    public function products()
    {
        return $this->hasMany('App\Models\ProductVariation', 'product_id');
    }
   
    public function categories()
    {
        return $this->belongsToMany('App\Models\Category', 'product_categories', 'product_id', 'category_id');
    }
    public function tags()
    {
        return $this->hasMany('App\Models\Tag');
    }
}

antigo/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Models\ProductCategory;
use App\Services\ProductService;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;

class ProductController extends Controller
{
    public function index(Request $request)
    {
        $products = ProductService::index($request);
        return view('admin.pages.product.index')
            ->with('products', $products);
    }
    public function create()
    {
        return view('admin.pages.product.create');
    }

    public function store(ProductRequest $request)
    {
        $product = ProductService::create($request->all());
        return \redirect()
            ->route('admin.product.edit', ['product' => $product])
            ->with('success', 'Produto cadastrado com sucesso');
    }
    public function edit(Product $product)
    {
        $categories = $product->categories;
        $tags = [];

        return view('admin.pages.product.edit')
            ->with('categories', $categories)
            ->with('tags', $tags)
            ->with('product', $product);
    }

    public function update(Product $product, ProductRequest $request)
    {
        ProductService::update($request->all(), $product);
        return \redirect()
            ->back()
            ->with('success', 'Produto editado com sucesso');
    }

    public function delete(Product $product)
    {
        ProductService::delete($product);
        return \redirect()
            ->back()
            ->with('success', 'Produto removido com sucesso');
    }
}

antigo/app/Http/Controllers/Customer/ProductController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Product;

class ProductController extends Controller
{
    public function index($slug)
    {
        $product = Product::where('slug', $slug)->first();

        return view('customer.pages.product.index')
            ->with('product', $product);
    }
}

antigo/resources/views/customer/pages/product/index.blade.php
@extends('customer.templates.default')
@section('content')
<section class="container p-section">
    <section id="box-title">
        <div class="container">
            <div class="row ">
                <div class="col d-flex justify-content-center">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{#}">Home</a></li>
                            <li class="breadcrumb-item">
                                {{$product->name}}</a>
                            </li>

                            @if($product->categories->first())
                            @if($product->categories->first()->category_id == null)
                            <li class="breadcrumb-item active" aria-current="page">
                                {{$product->categories->first()->name}}</li>
                            @else
                            <li class="breadcrumb-item active">
                                <a
                                    href="{{route('company',['category'=> $product->categories->first()->category->slug,'company' => $product->company->slug])}}">
                                    {{$product->categories->first()->category->name}}
                                </a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">
                                {{$product->categories->first()->name}}</li>
                            @endif
                            @endif
                        </ol>
                    </nav>
                </div>
            </div>

        </div>
    </section>

    <div class="row">
        <div class="col">
            <h3 class="block-title text-center">{{$product->name}}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div>
                <div class="box-product">
                    <div class="box-img-product">
                @foreach($product->images as $image)
                        <img src="{{asset('uploads/products/original/'.$image->file)}}" alt="{{$product->name}}">
                @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="container p-section">
    <div class="row">
        <div class="col">
            <div>
                <h4>R$ {{convertMoneyUsaToBrazil($product->promotional_price)}} <span class="product-price">R$
                        {{convertMoneyUsaToBrazil($product->price)}}</span> </h4>
                <h5>6x de R$ {{convertMoneyUsaToBrazil($product->promotional_price / 6)}}</h5>
            </div>
            
            <div>
                <form action="{{route('cart.store')}}" method="post">
                    @csrf
                    <input type="hidden" name="product_id" value="{{$product->id}}">
                    <button class="btn btn-primary btn-cart">
                        Comprar
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>

@endsection