antigo/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('/', 'Customer\HomeController@index');
Route::get('/search', 'Customer\SearchController@index')->name('search');
Route::get('/product/{slug}', 'Customer\ProductController@index')->name('product');
Route::get('/checkout', 'Customer\CheckoutController@index')->name('checkout');
Route::post('/checkout', 'Customer\CheckoutController@store')->name('store');

Route::group(['prefix' => 'carrinho', 'as' => 'cart.'], function(){
    Route::get('/', 'Customer\CartController@index')->name('index');
    Route::post('/cart', 'Customer\CartController@store')->name('store');

});


Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
Route::group(['prefix' => 'admin'], function(){
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::get('/register', 'Auth\RegisterController@showAdminRegisterForm')->name('admin.register');
    Route::post('/register', 'Auth\RegisterController@createAdmin');
    Route::post('/logout', 'Auth\RegisterController@logout')->name('admin.logout');

});

Route::get('/login/customer', 'Auth\LoginController@showCustomerLoginForm');
Route::get('/register/customer', 'Auth\RegisterController@showCustomerRegisterForm');
Route::post('/login/customer', 'Auth\LoginController@customerLogin');
Route::post('/register/customer', 'Auth\RegisterController@createCustomer');

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    // Categorias
    Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
    Route::group(['prefix' => 'categoria', 'as' => 'category.'], function () {
        Route::get('/', 'Admin\CategoryController@index')->name('index');
        Route::get('/create', 'Admin\CategoryController@create')->name('create');
        Route::post('/store', 'Admin\CategoryController@store')->name('store');
        Route::get('/edit/{category}', 'Admin\CategoryController@edit')->name('edit');
        Route::put('/update/{category}', 'Admin\CategoryController@update')->name('update');
        Route::delete('/delete/{category}', 'Admin\CategoryController@delete')->name('delete');
    });
    Route::group(['prefix' => 'variacao', 'as' => 'variation.'], function () {
        Route::get('/', 'Admin\VariationController@index')->name('index');
        Route::get('/create', 'Admin\VariationController@create')->name('create');
        Route::post('/store', 'Admin\VariationController@store')->name('store');
        Route::get('/edit/{variation}', 'Admin\VariationController@edit')->name('edit');
        Route::put('/update/{variation}', 'Admin\VariationController@update')->name('update');
        Route::delete('/delete/{variation}', 'Admin\VariationController@delete')->name('delete');
        Route::put('option/update/{option}', 'Admin\VariationController@optionUupdate')->name('option.update');
        Route::delete('option/delete/{option}', 'Admin\VariationController@optionDelete')->name('option.delete');
    });
    // Produtos
    Route::group(['prefix' => 'produtos', 'as' => 'product.'], function () {
        Route::get('/', 'Admin\ProductController@index')->name('index');
        Route::get('/create', 'Admin\ProductController@create')->name('create');
        Route::post('/store', 'Admin\ProductController@store')->name('store');
        Route::get('/edit/{product}', 'Admin\ProductController@edit')->name('edit');
        Route::put('/update/{product}', 'Admin\ProductController@update')->name('update');
        Route::delete('/delete/{product}', 'Admin\ProductController@delete')->name('delete');
        // Imagem do produto
        Route::group(['prefix' => '{product}/image', 'as' => 'image.'], function () {
            Route::post('/', 'Admin\ProductImageController@store')->name('store');
            Route::delete('/delete/{category}', 'Admin\ProductImageController@delete')->name('delete');
        });
        // Categoria do Produto
        Route::group(['prefix' => '{product}/category', 'as' => 'category.'], function () {
            Route::post('/', 'Admin\ProductCategoryController@store')->name('store');
            Route::delete('/delete/{category}', 'Admin\ProductCategoryController@delete')->name('delete');
        });
        // Tag do produto
        Route::group(['prefix' => '{product}/tag', 'as' => 'tag.'], function () {
            Route::post('/', 'Admin\ProductTagController@store')->name('store');
            Route::delete('/delete/{tag}', 'Admin\ProductTagController@delete')->name('delete');
        });
        // Variação do produto
        Route::group(['prefix' => '{product}/variation', 'as' => 'variation.'], function () {
            Route::post('/', 'Admin\ProductVariationController@store')->name('store');
            Route::delete('/delete/{variation}', 'Admin\ProductVariationController@delete')->name('delete');
        });
    });
});

    Route::get('table-list', function () {
        return view('pages.table_list');
    })->name('table');

    Route::get('typography', function () {
        return view('pages.typography');
    })->name('typography');

    Route::get('icons', function () {
        return view('pages.icons');
    })->name('icons');

    Route::get('map', function () {
        return view('pages.map');
    })->name('map');

    Route::get('notifications', function () {
        return view('pages.notifications');
    })->name('notifications');

    Route::get('rtl-support', function () {
        return view('pages.language');
    })->name('language');

    Route::get('upgrade', function () {
        return view('pages.upgrade');
    })->name('upgrade');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

antigo/resources/views/admin/includes/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="copyright">© ImaxCommerce. Todos os direitos reservados.</div>
    </div>
</footer>
</div>
</div>
<!--   Core JS Files   -->
<script src="{{ asset('material') }}/js/core/jquery.min.js"></script>
<script src="{{ asset('material') }}/js/core/popper.min.js"></script>
<script src="{{ asset('material') }}/js/core/bootstrap-material-design.min.js"></script>
<script src="{{ asset('material') }}/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<!-- Plugin for the momentJs  -->
<script src="{{ asset('material') }}/js/plugins/moment.min.js"></script>
<!--  Plugin for Sweet Alert -->
<script src="{{ asset('material') }}/js/plugins/sweetalert2.js"></script>
<!-- Forms Validations Plugin -->
<script src="{{ asset('material') }}/js/plugins/jquery.validate.min.js"></script>
<!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
<script src="{{ asset('material') }}/js/plugins/jquery.bootstrap-wizard.js"></script>
<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="{{ asset('material') }}/js/plugins/bootstrap-selectpicker.js"></script>
<!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
<script src="{{ asset('material') }}/js/plugins/bootstrap-datetimepicker.min.js"></script>
<!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
<script src="{{ asset('material') }}/js/plugins/jquery.dataTables.min.js"></script>
<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="{{ asset('material') }}/js/plugins/bootstrap-tagsinput.js"></script>
<!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{{ asset('material') }}/js/plugins/jasny-bootstrap.min.js"></script>
<!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
<script src="{{ asset('material') }}/js/plugins/fullcalendar.min.js"></script>
<!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
<script src="{{ asset('material') }}/js/plugins/jquery-jvectormap.js"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{{ asset('material') }}/js/plugins/nouislider.min.js"></script>
<!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
<!-- Library for adding dinamically elements -->
<script src="{{ asset('material') }}/js/plugins/arrive.min.js"></script>
<!--  Google Maps Plugin    -->
<!-- <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE'"></script> -->
<!-- Chartist JS -->
<script src="{{ asset('material') }}/js/plugins/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="{{ asset('material') }}/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{{ asset('material') }}/js/material-dashboard.js?v=2.1.1" type="text/javascript"></script>

<!-- Select 2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<!-- MaskMoney -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-maskmoney/3.0.2/jquery.maskMoney.min.js"></script>
<!-- Axios -->
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>

<script src="{{asset('js/mask.js')}}"></script>

<script type="text/javascript">
function slugify(string) {
    const a = 'àáäâãåăæçèéëêǵḧìíïîḿńǹñòóöôœøṕŕßśșțùúüûǘẃẍÿź·/_,:;'
    const b = 'aaaaaaaaceeeeghiiiimnnnooooooprssstuuuuuwxyz------'
    const p = new RegExp(a.split('').join('|'), 'g')
    return string.toString().toLowerCase()
        .replace(/\s+/g, '-') // Replace spaces with -
        .replace(p, c => b.charAt(a.indexOf(c))) // Replace special characters
        .replace(/&/g, '-and-') // Replace & with ‘and’
        .replace(/[^\w\-]+/g, '') // Remove all non-word characters
        .replace(/\-\-+/g, '-') // Replace multiple - with single -
    /*
    .replace(/^-+/, '') // Trim - from start of text
    .replace(/-+$/, '') // Trim - from end of text
    */
}
const createOptions = async (options, select) => {
    select.innerHTML = "<option disabled selected>Selecione..</option>";
    options.forEach((option) => {
        let optionElement = document.createElement('option');
        let textOption = document.createTextNode(option.name);
        optionElement.value = option.id;
        optionElement.appendChild(textOption);
        select.appendChild(optionElement)
    });
}

const validateError = (response) => {
    const {
        status
    } = response;
    if (status === 422) {
        const {
            data: {
                errors
            }
        } = response;

        for (error in errors) {
            let elementError = $(`input[name=${error}]`);
            let spanError = $(`#${error}-error`);

            elementError.addClass('is-invalid');
            elementError.parent().addClass('has-error');
            spanError.removeClass('display-none');
            spanError.text(errors[error]);
        }
    }
}

$('.btn-delete').on('click', function() {
    $('#delete-form').submit();
});

$('.input-slug').keyup(function() {
    var slug = slugify($(this).val());
    $(this).val(slug);
});
$(".input-money").maskMoney({
    thousands: '.',
    decimal: ',',
    allowZero: true,
    symbolStay: true
});
</script>

@yield('scripts')

antigo/resources/views/admin/includes/head.blade.php
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ __('Material Dashboard Laravel - Free Frontend Preset for Laravel') }}</title>
<link rel="apple-touch-icon" sizes="76x76" href="{{ asset('material') }}/img/apple-icon.png">
<link rel="icon" type="image/png" href="{{ asset('material') }}/img/favicon.png">
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
    name='viewport' />
<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css"
    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">

<!-- CSS Files -->
<link href="{{ asset('material') }}/css/material-dashboard.css?v=2.1.3" rel="stylesheet" />
<link rel="stylesheet" href="{{asset('css/admin.css')}}">

antigo/resources/views/admin/includes/modals.blade.php
@yield('modals')

antigo/resources/views/admin/includes/sidebar.blade.php
<form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
    <input type="hidden" name="_token" value="NKN81BvuQSzEbJlULUVrTDRewUlcAIJhPbOwli18"> </form>
<div class="wrapper ">
    <div class="sidebar" data-color="azure" data-background-color="white">
        <!--
                  Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

                  Tip 2: you can also add an image using data-image tag
              -->
        <div class="logo">
            <a href="http://imaxinformatica.com.br/" class="simple-text logo-normal">
                {{ __('ImaxCommerce') }}
            </a>
        </div>
        <div class="sidebar-wrapper">
            <ul class="nav">
                <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('admin.dashboard') }}">
                        <i class="material-icons">dashboard</i>
                        <p>{{ __('Dashboard') }}</p>
                    </a>
                </li>
                <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('admin.dashboard') }}">
                        <i class="material-icons">dashboard</i>
                        <p>{{ __('Pedidos') }}</p>
                    </a>
                </li>
                <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('admin.dashboard') }}">
                        <i class="material-icons">dashboard</i>
                        <p>{{ __('Clientes') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="collapse" href="#catalog" aria-expanded="true">
                        <i class="material-icons">category</i>

                        <p>{{ __('Catálogo') }}
                            <b class="caret"></b>
                        </p>
                    </a>
                    <div class="collapse show" id="catalog">
                        <ul class="nav">
                            <li class="nav-item{{ $activePage == 'product' ? ' active' : '' }}">
                                <a class="nav-link" href="{{ route('admin.product.index') }}">
                                    <i class="material-icons">trip_origin</i>
                                    <span class="sidebar-normal"> {{ __('Produtos') }} </span>
                                </a>
                            </li>
                            <li class="nav-item{{ $activePage == 'category' ? ' active' : '' }}">
                                <a class="nav-link" href="{{ route('admin.category.index') }}">
                                    <i class="material-icons">trip_origin</i>
                                    <span class="sidebar-normal">{{ __('Categorias') }} </span>
                                </a>
                            </li>
                            <li class="nav-item{{ $activePage == 'category' ? ' active' : '' }}">
                                <a class="nav-link" href="{{ route('admin.category.index') }}">
                                    <i class="material-icons">trip_origin</i>
                                    <span class="sidebar-normal">{{ __('Tags') }} </span>
                                </a>
                            </li>
                            <li class="nav-item{{ $activePage == 'category' ? ' active' : '' }}">
                                <a class="nav-link" href="{{ route('admin.category.index') }}">
                                    <i class="material-icons">trip_origin</i>
                                    <span class="sidebar-normal">{{ __('Fornecedores') }} </span>
                                </a>
                            </li>
                            <li class="nav-item{{ $activePage == 'category' ? ' active' : '' }}">
                                <a class="nav-link" href="{{ route('admin.category.index') }}">
                                    <i class="material-icons">trip_origin</i>
                                    <span class="sidebar-normal">{{ __('Marcas') }} </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
                    <a class="nav-link" href="{{ route('admin.dashboard') }}">
                        <i class="material-icons">dashboard</i>
                        <p>{{ __('Banners') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('admin.variation.index')}}">
                        <i class="material-icons">library_books</i>
                        <p>{{ __('Variações') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('table') }}">
                        <i class="material-icons">content_paste</i>
                        <p>{{ __('Table List') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('icons') }}">
                        <i class="material-icons">bubble_chart</i>
                        <p>{{ __('Icons') }}</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('map') }}">
                        <i class="material-icons">location_ons</i>
                        <p>{{ __('Maps') }}</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <a class="navbar-brand" href="#">{{$titlePage}}</a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
                    aria-expanded="false" aria-label="Toggle navigation">

                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end">
                    <!-- <form class="navbar-form">
                        <span class="bmd-form-group">
                            <div class="input-group no-border">
                                <input type="text" value="" class="form-control" placeholder="Pesquisar...">
                                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                    <i class="material-icons">search</i>
                                    <div class="ripple-container"></div>
                                </button>
                            </div>
                        </span>
                    </form> -->
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('admin.dashboard') }}">
                                <i class="material-icons">dashboard</i>
                                <p class="d-lg-none d-md-block">
                                    Stats
                                </p>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="navbarNotifications"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">notifications</i>
                                <span class="notification">3</span>
                                <p class="d-lg-none d-md-block">
                                    Notificações
                                </p>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarNotifications">
                                <a class="dropdown-item" href="#">Novo pedido</a>
                                <a class="dropdown-item" href="#">Novo cliente</a>
                                <a class="dropdown-item" href="#">Novo orçamento</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">person</i>
                                <p class="d-lg-none d-md-block">
                                    Account
                                </p>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                                <a class="dropdown-item" href="{{ route('profile.edit') }}">Perfil</a>
                                <a class="dropdown-item" href="#">Configurações</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ route('admin.logout') }}"
                                    onclick="event.preventDefault();document.getElementById('logout-form').submit();">Log
                                    out</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>